### ISSUE TITLE
Missing import

### ISSUE THREAD

**Issue by Laurens-T** [iamshaunjp/node-express-jwt-auth#2]
Lesson-17 adds the `checkUser` method to `authMiddleware.js`, the import for the `User` model is missing however.

**Comment by ahctun** [comment]
It's surely missing. I created a pull request for this same issue here: https://github.com/iamshaunjp/node-express-jwt-auth/pull/10#issue-712746962
@iamshaunjp

**Comment by Laurens-T** [comment]
Cool, I had forgotten this existed.
